services:
  xingyiquan:
    container_name: xingyiquan
    image: registry.cn-shenzhen.aliyuncs.com/tmd/xyq:latest
    ports:
      - "8080:80"
    volumes:
      - "../data:/usr/share/nginx/html/data"
    restart: unless-stopped
    networks: 
      - infrastructure
      - saas
      - app
      
# ==================== 网络 ====================      
networks:
  infrastructure:
    external: true
  saas:
    external: true
  app:
    external: true 